version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sTurista123
      POSTGRES_DB: sTuristadb
    container_name: sTurista
    volumes:
      - ./postgres:/var/lib/postgresql/data1
    
